# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!  

target 'SZ_Swift_weibo' do  

pod 'SDWebImage'

pod 'Alamofire', '~> 4.5'

pod 'SnapKit', '~> 4.0.0'

pod 'YYModel'

pod 'FMDB'

pod 'AFNetworking'

pod 'SVProgressHUD'

pod 'pop'

end  
